### ISSUE TITLE
application failed to load because it could not find or load the Qt platform plugin "windows" in "",

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#31]
I tried installing Janus from a PC with a fresh install of windows 10 and I'm getting an error like below:

https://i.imgur.com/IciCNAT.png

Weird since these plugins are all located in the platforms/ folder where janusvr is installed.

**Comment by JamesMcCrae** [comment]
Should be fixed in commit https://github.com/janusvr/janus/commit/ab034136d31f06f5a03308fd66d652e1a6c349b4

Build servers should pull this change and incorporate it.  Let me know if you still experience the issue and we can re-open (I've tested on a clean Win 10 install with success, using the updated platforms/q*.dll's).
