### ISSUE TITLE
Bug: Run animation stuck when running then not letting go of shift

### ISSUE THREAD

**Issue by source83** [janusvr/janus#52]
Reproduce by holding shift, then move forward then let go of "w" but continue holding "shift".
The same forward running animation is stuck until "shift" is released.

**Comment by JamesMcCrae** [comment]
Fixed in commit https://github.com/janusvr/janus/commit/a31641099f09d06a6d4efabf3eb3a4a894cb26c5

**Comment by source83** [comment]
This worked, but it created new bugs:
1: if you hold run then a direction, the animation doesn't trigger for whatever direction.
2: if you walk forward (or any other direction) then hold shift the run animation triggers, but when you let go of the direction or change direction. the animation goes back to idle and doesn't change until shift and any direction is released.

**Comment by JamesMcCrae** [comment]
Testing both looking at my own avatar locally in the menu, and launching two clients and watching the other.

1.  There is only one "run" animation (looks like running forward) that is used for all directions.  Is this what you mean?  Because I do see the "run" animation start.
2.  Walk forward (W), hold shift, let go of forward (W), get idle animation (as expected).  Still holding shift, press any of W,A,S,D and the run animation plays (as expected).

Are you sure you are using the latest build (either 62.10 or above that has this fix)?

**Comment by source83** [comment]
sorry, I revise my bug, it was related to the avatar animations.
